### ISSUE TITLE
Running test on windows

### ISSUE THREAD

**Issue by jeancroy** [atom/scandal#30]
I tried to run the test on my window machine with this to report:

1. Pretty much all "file doesn't exist" make jasmine fail because of ENOENT error.
  - I understand the error is expected, just somehow jasmine fail to catch it and make it a test success.

2. ChunkedLineReader -> it works with multibyte characters in utf8 (L158)
 - 9 of those test fail

3. search ->  when there is no error ->  it finds matches in a file (L28)
  - you are using a regex with a hard-coded forward slash "/",  window use backward.

----

Failure of 2: migth have real life implication for user of windows.
Faillure of 3: a character class with both slash migth be a quick fix.

Faillure of 1: ???

I tougth it migth be my install of jasmine, tryed to install with `npm install`. `apm install`. deleted folder reinstall. copy paste jasmine from another node project, none worked.

**Comment by benogle** [comment]
Can you try on master now. I removed the forward slashes in https://github.com/atom/scandal/commit/0d1cd85c6b26b4616c0c2cf4baa6492e809e01b4
